### ISSUE TITLE
Hello I have problem with using multiple java file

### ISSUE THREAD

**Issue by ghazalialshafi** [Techno-Developer/Java2Smali#2]
when I use multiple java file by Import keyword or library error say that file not found
can you guide me how to use it for multiple import comand.

**Comment by Belluxx** [comment]
If you mean that you are getting errors when trying to convert java files that contain imports to non-standard libraries, it's normal. Java2Smali needs to have all the required sources inside the directory that you are converting.

So if you use a third party library, you should include it in the sources manually.
